" use client"

import './globals.css'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'

export const metadata = {
  title: 'sachin react',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Navbar/>
      
        {children}

      <Footer/>
        </body>
    </html>
  )
}
